---
title: "DSCI 445 - Algal Blooms"
author: "Dawson Eliasen, Boston Lee, Miles Austin"
date: "12/7/2020"
output:
  pdf_document: default
---

```{r setup, echo=FALSE}
library(knitr)
opts_chunk$set(engine.path='venv/bin/python3')
```

```{python, include=FALSE}
from plots import *
```

# Background

  Algae blooms are becoming more relevant in today’s world, due to the increasing 
climate change. Scientific research has shown that algae blooms are happening at
an increasing frequency, with a higher geographic distribution than we had 
previously seen, which is especially notable in high elevation reservoirs. Not 
only are algae blooms occurring more frequently, harmful algal blooms - also 
known as HABS - are also occurring more frequently.  


  Even though algae are natural and part of a healthy freshwater ecosystem, the
algae can grow to an extent that it can be harmful to the ecosystem – creating 
anoxic conditions for example, otherwise known as “dead zones” for the aquatic 
fauna. The HABs can produce toxins that can be harmful to not only the aquatic 
ecosystem, but to humans and other animals, such as dogs. Both algae blooms and 
HABs have a wide range of impacts that can not only be local, but they can also
have interstate impacts. This is especially important to note because Lake Erie,
in 2014, had a HAB that was incredibly impactful to the local economy and 
residents. The HAB left half-a-million people without clean water to drink and 
roughly \$65 million in economic losses over a two day span of time.
            
  With the increasing use of reservoirs for municipalities, the quality of the 
water is very important. Although the water gets treated before it gets to the 
tap, the quality of the water as it reaches the water treatment plant is very 
important regarding the cost to treat the water for municipal use, and algal 
blooms impact the quality of the water dramatically. Most municipal water is 
monitored, but not all of the data is publicly available and some isn’t 
monitored in situ - otherwise known as collected by hand. However, Landsat is a
series of satellites that image the Earth surface, in repeated intervals of 14 
days; that is to say Fort Collins gets re-imaged every 14 days. Landsat 5 dates
back to 1984, and is no longer taking images, while landsat 7 (1999) and landsat
8 (2013) still record images today. The landsat imagery allows for a larger 
sample of data to look at the trends of algal blooms in Colorado, in comparison 
to the lack of public in situ data available. Figure 1 shows reservoirs - only 
those greater than 0.01 km² -  that have both in situ and satellite imagery in 
blue, while the reservoirs in red indicate the reservoirs with just the landsat 
imagery available. It is easy to see the lack of reservoir data we have 
available to us, which is why utilizing machine learning to try and predict 
algae blooms from just remotely sensed imagery would be an incredibly useful
method of determining water quality in reservoirs. 


# Methods

TODO:
How we got the data

## Data Interpolation (Merging Shift Threshold)

Tried 5 variables
+/- day merge
Tried day threshold

The insitu data was not collected as frequently as the satellite imagery data.
To remedy this, an experimental approach was taken in which the FIXME data
was shifted by a certain number of days forward and backward. Intuitively, algae
blooms do not drastically alter the characteristics of a lake between consecutive days.
Interpolating surrounding observations with existing data allowed for many more
of the satellite observations to be used, even though there was no insitu data
accompanying the observations. 

However, the aforementioned Interpolating approach certainly fails after a
certain range of days. The optimal shift was determined experimentally: Each
model was fit using data shifted from one to ten days in either direction, and
the cross-validation error was used to assess model accuracy. The specifics of
the experimental structure are described below. The model accuracy provided a
picture of the quality of interpolation provided by each shift. If data was
shifted too many days, the prediction accuracy of the algorithm should
deteriorate.

## Response Variable Transformation

As can be seen from Figure \ref{fig:resp-hist}, the chlorophyll variable, the response
variable in this case, was initially highly skewed. This had an impact on
initial prediction accuracy. In order to correct for the skewed nature of the
data, the response was log-transformed, yielding the second distribution in
Figure \ref{fig:resp-hist}.

```{python, echo=FALSE, fig.cap="Distribution of chlorophyll before and after log transformation.\\label{fig:resp-hist}"}
plot_histograms()
```

It should be noted that all MSE values were calculated from chlorophyll on the
log-transformed scale, then exponentiated to account for the variable
transformation.

## Models

The algae bloom data is spatiotemporal; the blooms are recorded in a certain
geographic location at a certain time. This makes the class of linear models
unsuitable for this problem. Linear models make assumptions about the structure
of the errors in the data generating process that are violated by spatiotemporal
data. Spatiotemporal data has errors which are correlated; as observations
closer in space or time will covary (CITE). 

To work around the issue of violated assumptions in classical statistical
models, we opted to use three variants of non-parametric, tree based regression
models. The models used were Random Forest, Gradient Boosting and XGBoost. These
models do not make assumptions about the structure of errors and correlations in
the data, meaning spatiotemporal data is usable.

TODO Describe each model?

## Model Selection

Train/test split? ($\frac{1}{3}$ was held out)
Experimental variables were compared using 5-fold cross validation

# Results

## Merge Shifting Threshold

Comparing across different shifting thresholds, all three models included in
the experiment performed similarly. 

```{python, echo=FALSE, fig.cap="Cross-validation error for all three models at merge thresholds from 1 to 10.\\label{fig:thresh-performance}"}
plot_thresh_performance()
```

As we can see from Figure \ref{fig:thresh-performance}, the trend across merge
thresholds for each model is very similar. As can also be seen in Figure
\ref{fig:thresh-performance}, the optimal shifting threshold is three
days \ref{fig:thresh-performance}. It is also interesting to note that a shift of one day performed
worse than no shift, or a shift of two days. This is a counterintuitive result,
but it could be due to the tradeoff between the extra volume of data added by
larger shift thresholds versus the accuracy of the data at lower shifting
thresholds.


## Model Performance

All three models mentioned performed similarly, with no model greatly exceeding
the other two in terms of CV error. The best overall model, in terms of FIXME
error, was a random forest with a merge shift threshold of three days, that
included all features. The best model had a CV MSE of approximately 1.75, and a
test MSE of approximately 1.09.
